# version: '3.8'  # Убираем устаревший атрибут

services:
  # Python Flask бэкенд
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: clicker-backend
    restart: unless-stopped
    volumes:
      - backend_data:/app/data
    user: "1000:1000"
    environment:
      - FLASK_ENV=production
    networks:
      - clicker-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx фронтенд
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: clicker-frontend
    restart: unless-stopped
    ports:
      - "8080:80"  # Используем порт 8080 вместо 80
      - "8443:443" # Используем порт 8443 вместо 443
    depends_on:
      - backend
    networks:
      - clicker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

# Сети
networks:
  clicker-network:
    driver: bridge

# Тома для данных
volumes:
  backend_data:
    driver: local 